name: Laravel CI

on:
  push:
    branches:
      - main  # Set a branch name to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_HOST: sql11.freemysqlhosting.net
      DB_PORT: 3306
      DB_DATABASE: sql11644660
      DB_USERNAME: sql11644660
      DB_PASSWORD: JF8QVUte7V

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'  # adjust as per your PHP version

      - name: Install Dependencies
        run: composer install

      - name: Run Tests
        run: ./vendor/bin/phpunit
