name: Laravel CI

on:
  push:
    branches:
      - main  # Set a branch name to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      #DB
      DB_HOST: sql11.freemysqlhosting.net
      DB_PORT: 3306
      DB_DATABASE: sql11644660
      DB_USERNAME: sql11644660
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      #Mailer
      MAIL_MAILER: smtp
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USERNAME: elidonneziri@gmail.com
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      MAIL_ENCRYPTION: ssl
      MAIL_FROM_ADDRESS: "elidonneziri@gmail.com"
      MAIL_FROM_NAME: "${APP_NAME}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'  # adjust as per your PHP version
          tools: composer, cs2pr

      - name: Install Dependencies
        run: composer install

      - name: Run PHP_CodeSniffer
        run: ./vendor/bin/phpcs ./app/

      - name: Run Tests
        run: ./vendor/bin/phpunit
